## PyTroch

`Pytorch` is an open source deeplearning framework. it is dynamicaly featured framework. it is easy to learn.

Most of the Deep Learning research Papers are written in **PyTorch**.

In [1]:
import torch
print(torch.__version__)

2.13.0+cpu


## shapes and dimensions

In pytorch mismatched the shapes and dimensions while matrix maultiplications. which is caused an error.

In [2]:
# scaler is the 0 dimension

scaler = torch.tensor(7)
print(f'Scaler : {scaler}')
print(f"scaler shape : {scaler.shape}")
print(f"scaler dimension : {scaler.ndim}")
print(f"scaler item : {scaler.item()}")

Scaler : 7
scaler shape : torch.Size([])
scaler dimension : 0
scaler item : 7


In [3]:
# vector is the series of numbers

vector = torch.tensor([1,2,3,4,5,6,7,8])
print(f"vector : {vector}")
print(f'vector shape : {vector.shape}')
print(f'vector dimension : {vector.ndim}')


vector : tensor([1, 2, 3, 4, 5, 6, 7, 8])
vector shape : torch.Size([8])
vector dimension : 1


In [4]:
matrix = torch.tensor([
    [2,3,4],
    [5,3,7],
    [5,7,8]
])

print(f"matrix : {matrix}")
print(f"matrix shape : {matrix.shape}")
print(f"matrix dimensions : {matrix.ndim}")

matrix : tensor([[2, 3, 4],
        [5, 3, 7],
        [5, 7, 8]])
matrix shape : torch.Size([3, 3])
matrix dimensions : 2


In [7]:
tensor = torch.randint(10, 100, size=(1, 4, 4))
print('Tensor', tensor)
print('Tensor shape :', tensor.shape)
print('Tensor Dimension', tensor.ndim)

Tensor tensor([[[13, 81, 70, 34],
         [62, 70, 44, 72],
         [11, 64, 32, 13],
         [10, 61, 14, 71]]])
Tensor shape : torch.Size([1, 4, 4])
Tensor Dimension 3


## Random Tensors
1. `torch.rand(size=())` --> random numbers
2. `torch.randint()`  --> random integers
3. `torch.ones()` --> dummy ones
4. `torch.zeros()` --> zeros

In [8]:
torch.rand(size=(4,4,4))

tensor([[[0.0474, 0.8634, 0.6682, 0.5753],
         [0.7235, 0.3670, 0.2775, 0.5624],
         [0.7731, 0.8619, 0.3243, 0.7372],
         [0.4925, 0.6294, 0.6602, 0.8195]],

        [[0.8153, 0.5568, 0.6215, 0.3451],
         [0.7047, 0.6117, 0.0054, 0.4459],
         [0.3839, 0.7534, 0.9026, 0.1924],
         [0.8055, 0.5390, 0.2413, 0.2131]],

        [[0.4490, 0.6127, 0.1450, 0.7397],
         [0.0840, 0.4960, 0.1117, 0.5859],
         [0.9959, 0.9076, 0.8049, 0.4652],
         [0.0621, 0.8911, 0.7369, 0.4271]],

        [[0.3559, 0.5227, 0.5273, 0.9919],
         [0.5678, 0.1585, 0.6775, 0.8482],
         [0.7249, 0.8012, 0.4318, 0.2680],
         [0.7477, 0.1082, 0.4523, 0.1243]]])

In [13]:
torch.randint(20, 30, size=(3,3)) # Mention here what is the start value and end value

tensor([[25, 25, 28],
        [20, 21, 25],
        [29, 20, 22]])

In [9]:
torch.ones(size=(2,2,2))

tensor([[[1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.]]])

In [10]:
torch.zeros(size=(3,3,3))

tensor([[[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]])

## Tensor Datatypes 
There are so many tensor datatypes available in pytorch. so visit official to checkout many datatypes.

Let us see some of the datatypes to understand.

#### Some Datatypes:
1. torch.float16
1. torch.float32
1. torch.float64
1. torch.int16
1. torch.int32
1. torch.int64
***

*Note :*

Datatype Missmatching error is the one of the biggest error in pytorch try to use same datatypes to avoid errors.

In [15]:
tensor_float16 = torch.rand(size=(3,3), dtype=torch.float16)
print(f'dtype : {tensor_float16.dtype}')

dtype : torch.float16


In [16]:
tensor_float32 = torch.rand(size=(3,3), dtype=torch.float32)
print(f'dtype : {tensor_float32.dtype}')

dtype : torch.float32


In [17]:
tensor_float64 = torch.rand(size=(3,3), dtype=torch.float64)
print(f'dtype : {tensor_float64.dtype}')

dtype : torch.float64


In [25]:
tensor_int16 = torch.randint(2, 20,size=(3,3), dtype=torch.int16)
print(f'dtype : {tensor_int16.dtype}')

dtype : torch.int16


## Tensor device

**Tensor** runs on (`CPU` or `GPU`), but `GPU` runs better than `CPU`.

`GPU` Performs Matrix operations very well. In Deep Learning matrix multiplication is used.

**PyTorch** defaultly tensors runs on `CPU` we want to tells to run in `GPU`.

Device agnoistic code.

In [26]:
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cpu'

## Manipulating Tensors

Such as:

1. Addition
2. Subtraction
3. Multiplication (element-wise multiplication)
4. Division
5. Matrix Multiplication

In [36]:
torch.manual_seed(42)
torch.rand(size=(2, 2)) + torch.rand(size=(2,2))

tensor([[1.2727, 1.5159],
        [0.6394, 1.7529]])

In [37]:
torch.manual_seed(42)
torch.rand(size=(2, 2)) - torch.rand(size=(2,2))

tensor([[0.4918, 0.3141],
        [0.1263, 0.1657]])

In [38]:
torch.manual_seed(42)
torch.rand(size=(2, 2)) * torch.rand(size=(2,2))

tensor([[0.3445, 0.5498],
        [0.0982, 0.7613]])

In [50]:
%%time  

torch.manual_seed(42)
torch.rand(size=(2, 2)) @ torch.rand(size=(2,2)) # @ perporforms matrix multiplication

CPU times: user 1.42 ms, sys: 0 ns, total: 1.42 ms
Wall time: 1.18 ms


tensor([[0.5792, 1.2563],
        [0.3956, 0.9914]])

In [51]:
%%time

torch.manual_seed(42)
torch.matmul(torch.rand(size=(2, 2)), torch.rand(size=(2,2))) # torch.matmul() is faster than @

CPU times: user 1.43 ms, sys: 39 μs, total: 1.47 ms
Wall time: 1.02 ms


tensor([[0.5792, 1.2563],
        [0.3956, 0.9914]])

## Shape Error

Another important error is shape error. The two tensors must have in same inner shapes.

example:
***
1. The inner dimensions must match:

~~~
(3, 2) @ (3, 2) won't work
(2, 3) @ (3, 2) will work
(3, 2) @ (2, 3) will work
~~~
2. The resulting matrix has the shape of the outer dimensions:

~~~
(2, 3) @ (3, 2) -> (2, 2)
(3, 2) @ (2, 3) -> (3, 3)
~~~

In [43]:
torch.manual_seed(42)
try:
    torch.rand(size=(3, 2)) @ torch.rand(size=(3, 2))
except Exception as e:
    print(e)

mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)


In [44]:
torch.manual_seed(42)
mat1 = torch.rand(size=(2, 3))
mat2 = torch.rand(size=(3, 2))

print(f"Matrix Multiplication : {mat1 @ mat2}")
print(f"Matrix Shape : {(mat1 @ mat2).shape}")

Matrix Multiplication : tensor([[1.4450, 1.0493],
        [1.1750, 1.1700]])
Matrix Shape : torch.Size([2, 2])


## Transpose

`torch.transpose(input, dim=0, dim=1)` - Where `input` is desired input tensor

`tensor.T` to transpose the tensor. rows to cols and cols to rows.

In [54]:
a = torch.randint(20, 45, size=(3, 2))
print(f"Tensor : {a}")
print(f"Original Shape : {a.shape}")
print(f"Transposed Tensor : {a.T}")
print(f"Transposed Tensor Shape: {a.T.shape}")

Tensor : tensor([[44, 21],
        [43, 31],
        [44, 33]])
Original Shape : torch.Size([3, 2])
Transposed Tensor : tensor([[44, 43, 44],
        [21, 31, 33]])
Transposed Tensor Shape: torch.Size([2, 3])


## Linear nn

**Neural Network** full of matrix multiplication.
`torch.nn.Linear` is see in later,  it is feedforward layer or (fully connected layer), implements matrix multiplications 

between input x and output y.

```y = mx + b```

In [66]:
torch.manual_seed(42)

linear = torch.nn.Linear(in_features=2,
                         out_features=6)

In [67]:
tensor_a = torch.randint(1, 10, size=(3, 2), dtype=torch.float32)
print(f"tensor : {tensor_a}")
print(f'tensor shape : {tensor_a.shape}')

tensor : tensor([[4., 5.],
        [5., 9.],
        [2., 6.]])
tensor shape : torch.Size([3, 2])


In [68]:
output = linear(tensor_a)
print(f'output : {output}')
print(f'output shape: {output.shape}')

output : tensor([[ 5.6194,  2.6809,  0.4347,  0.5995,  0.4447,  3.2247],
        [ 8.5076,  5.1135,  0.8505,  1.9163, -1.0070,  4.3687],
        [ 5.1251,  3.6618,  0.8872,  1.7033, -1.3207,  2.1278]],
       grad_fn=<AddmmBackward0>)
output shape: torch.Size([3, 6])


## Aggregation functions
1. `torch.max()`  --> max element
2. `torch.min()` --> min element
3. `torch.mean()` --> average of tensor
4. `torch.mode()` -->  most frequency element
5. `torch.arange()` --> produce range of numbers.

In [70]:
a = torch.arange(start=20, end=200, step=5)
print(a)

tensor([ 20,  25,  30,  35,  40,  45,  50,  55,  60,  65,  70,  75,  80,  85,
         90,  95, 100, 105, 110, 115, 120, 125, 130, 135, 140, 145, 150, 155,
        160, 165, 170, 175, 180, 185, 190, 195])


In [71]:
"Max", torch.max(a)

('Max', tensor(195))

In [72]:
"Min", torch.min(a)

('Min', tensor(20))

In [74]:
"Mean", torch.mean(a, dtype=torch.float)

('Mean', tensor(107.5000))

In [75]:
"Mode", torch.mode(a)

('Mode',
 torch.return_types.mode(
 values=tensor(20),
 indices=tensor(0)))

## Reshaping, stacking, squeezing and unsqueezing

|Method|Description|
|---|---|
|`torch.reshape(input, shape)`|Reshapes `input` to `shape`, if also used `torch.Tensor.reshape()`.|
|`torch.view()`|Returns a view of the original tensor in a different shape but shares the same data as the original tensor.|
|`torch.stack(tensors, dim=0)`|Concatenates a sequence of `tensors` along a new dimension ( `dim` ), all `tensors` must be same size.|
|`torch.squeeze(input)`|Squeezes `input` to remove all the dimenions with value1.|
|`torch.unsqueeze(input, dim)`|Returns `input` with a dimension value of 1 added at `dim`.|
|`torch.permute(input, dim)`|Returns a view of the original `input` with its dimensions permuted (rearranged) to `dims` .|

### Reshape

In [80]:
x = torch.arange(1, 7)
print(x)
print(x.shape)

print('-------')
print(x.reshape(3, 2))
print(x.reshape(3, 2).shape)

print('-------')
print(x.reshape(2, 3))
print(x.reshape(3, 2).shape)

tensor([1, 2, 3, 4, 5, 6])
torch.Size([6])
-------
tensor([[1, 2],
        [3, 4],
        [5, 6]])
torch.Size([3, 2])
-------
tensor([[1, 2, 3],
        [4, 5, 6]])
torch.Size([3, 2])


### View

In [84]:
print('original x', x)
print('viewd x', x.view(3,2))

original x tensor([1, 2, 3, 4, 5, 6])
viewd x tensor([[1, 2],
        [3, 4],
        [5, 6]])


### Stack

In [90]:
a = torch.tensor([2, 4])
b = torch.tensor([5, 6])

print(torch.stack([a, b], dim=0))
print(torch.stack([a, b], dim=1))

tensor([[2, 4],
        [5, 6]])
tensor([[2, 5],
        [4, 6]])


### Squeeze

In [97]:
a2 = torch.rand(size=(1, 3, 3))
print(a2)
print(a2.shape)
print(a2.ndim)
print('-'*40)

print(a2.squeeze())
print(a2.squeeze().shape)
print(a2.squeeze().ndim)
print('-'*40)

tensor([[[0.2018, 0.9497, 0.6666],
         [0.9811, 0.0874, 0.0041],
         [0.1088, 0.1637, 0.7025]]])
torch.Size([1, 3, 3])
3
----------------------------------------
tensor([[0.2018, 0.9497, 0.6666],
        [0.9811, 0.0874, 0.0041],
        [0.1088, 0.1637, 0.7025]])
torch.Size([3, 3])
2
----------------------------------------


### Unsqueeze

In [102]:
a3 = torch.rand(size=(1, 3, 3))
print(a3)
print(a3.shape)
print(a3.ndim)
print('-'*40)

print(a3.unsqueeze(dim=1))
print(a3.unsqueeze(dim=1).shape)
print(a3.unsqueeze(dim=1).ndim)

tensor([[[0.1716, 0.3336, 0.5782],
         [0.0600, 0.2846, 0.2007],
         [0.5014, 0.3139, 0.4654]]])
torch.Size([1, 3, 3])
3
----------------------------------------
tensor([[[[0.1716, 0.3336, 0.5782],
          [0.0600, 0.2846, 0.2007],
          [0.5014, 0.3139, 0.4654]]]])
torch.Size([1, 1, 3, 3])
4


### Permute

In [106]:
xtensor = torch.rand(size=(2, 3, 3))
print(xtensor.shape)

torch.Size([2, 3, 3])


In [107]:
x = xtensor.permute(2, 1,0 )
print(x.shape)

torch.Size([3, 3, 2])


In [108]:
x = xtensor.permute(1,0,2 )
print(x.shape)

torch.Size([3, 2, 3])


## End
Now fundamentals are completed .
***
Next *Workflow of pytorch*